service: cart-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-3

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: '/{proxy+}'

useDotenv: true